title = "Notre-Dame de Paris"
baseURL = "https://example.com"
languageCode = "en-us"
theme = "website-ananke"
themesDir = ".."
resourceDir = "resources"

Copyright = "Non-Human Party"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

# https://portfolio.peter-baumgartner.net/2017/09/10/how-to-install-disqus-on-hugo/
DisqusShortname = "nonhuman"

[languages]
  [languages.en]
    title = "ğŸ¤–ğŸ’ƒğŸ¦˜"
    weight = 1
    contentDir = "content/en"
  [languages.fr]
    title = "ğŸ¤–ğŸ’ƒğŸ¸"
    weight = 2
    contentDir = "content/fr"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  site_logo = ""
  description = "The last theme you'll ever need. Maybe."
  facebook = ""
  twitter = "https://twitter.com/GoHugoIO"
  instagram = ""
  youtube = ""
  github = ""
  gitlab = ""
  linkedin = ""
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = ""
  # Color classes are defined in /assets/ananke/css/_tachyons.css
  background_decorative_class = "bg-pink"
  background_reading_class = "bg-solarized-light"
  cover_dimming_class = "dimming"
  featured_image = "/images/gohugo-default-sample-hero-image.jpg"
  recent_posts_number = 2